### ISSUE TITLE
[Dev][Tips] Dynamically fetch list of tips

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#384]
Currently, the[ tips](https://github.com/saucelabs/elemental-next/blob/main/frontend/src/pages/tips.js) page is using a [hardcoded file](https://github.com/saucelabs/elemental-next/blob/main/frontend/src/data.js) to create the tips page. 
It should be fetching all the [docs](https://github.com/saucelabs/elemental-next/tree/main/frontend/docs/updated-tips) files. 
It seems that fetching data from a markdown file to display part of its content an enable a filter is not trivial. 

## Acceptance Criteria

- [ ] Fetch data from docs markdown metadata and display it in the Tips Page as a card
- Display title and description only
- Add level and tags later in other issues
![Image](https://user-images.githubusercontent.com/7980624/229583959-1a3d0f7b-afec-4a3f-b1a2-5ac5f24ab7ea.png)

**Comment by daniellemadry** [comment]
So with the research I've done so far, we may be able to do it using MDXProvider component. I will try it out today and see if it works. [](https://mdxjs.com/packages/react/ )

**Comment by spider-sauce** [comment]
Hey all, I added the `getFrontmatter.js` script and it needs review. I tested it locally and it works but I didn't want to commit the completed file because it would involve rebuilding the site—which would involve 589 or so changes 😨 

This takes care of fetching the frontmatter dynamically and outputting it to a file to use in the website before it's built.

## TODO

- We need to refactor `tips.js`, or change the output directory in `getFrontmatter.js` so the two can work in tandem
- We need to do some UAT before we can close this issue out to ensure everything displays correctly.

**Comment by aquaomarine** [comment]
Follow up for this issue will be Issue #464

**Comment by discombobulateme** [comment]
@aquaomarine do you have a solution? can this issue be closed?

**Comment by discombobulateme** [comment]
Solved my adding https://mdxjs.com/ as a script folder 
Closed in the #459 PR
