### ISSUE TITLE
[Dev][Bugs]Fix pre launch several issues

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#590]
- [x] The selenium slack link in the footer is broken and goes to a "this link is dead" message
- [x] The selenium slack link in the Get Involved page takes you to the sauce labs CTA to "join our community", is that correct?
- [x] The subtitle text on the landing page is broken and showing up as a different size type
- [x] The nav bar is strangely stretched and lacks the spacing between elements
- [x] The spacing on the filters for the tips page is far too spaced out
- [ ] Chosing "testing" on the filter by categories locks you out of any dropdowns
- [ ] The left hand menu is still visible on every tips page and has the condensed titles from the github instead of the actual titles

**Comment by discombobulateme** [comment]
@Globnartheexquisite I do not understand those 2 items: 
 

- [ ] The subtitle text on the landing page is broken and showing up as a different size type --> do you mean... it should have 3 lines and its in one with a different header size? What do you mean by broken?

- [ ] The nav bar is strangely stretched and lacks the spacing between elements --? Could you provide an image?  I am wondering we are seeing different things in different screen sizes as it is responsible

**Comment by Globnartheexquisite** [comment]
@discombobulateme 
Re: landing page text. The subtitle "A free weekly email..." is set in the same size type as the body copy, in the prototype it is set in 200 Roboto 28pt (2.33 rem), on the landing page it is set in 400 Roboto 19.2pt (1.6 rem). 

Re: Nav Bar. The elements on the right side of the nav bar are spaced by 37pt (3.08 rem). In the deployed site they are spaced out significantly less. The bar is also stretched side to side instead of reaching its max extension as depicted in frame Content Landing Page - Stretched. 

Additional Notes: The cards are huge, they don't need to be nearly that large, as it currently stands they look like they're waiting on large swaths of additional content. Reference frame Content Landing Page in the figma for more information.

**Comment by discombobulateme** [comment]
This issue fixed several issues. 
Opening individual issues for the missing items as they are more complicated to fix: 

- [ ]  Chosing "testing" on the filter by categories locks you out of any dropdowns
- [ ] The left hand menu is still visible on every tips page and has the condensed titles from the github instead of the actual titles
